/*
Package appinfo GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package appinfo

import (
	context "context"
)

type contextInfo struct{}

func InfoFromContext(ctx context.Context) (*Info, bool) {
	if v, ok := ctx.Value(contextInfo{}).(*Info); ok {
		return v, true
	}
	return nil, false
}

func InfoInjectContext(ctx context.Context, tpe *Info) context.Context {
	return context.WithValue(ctx, contextInfo{}, tpe)
}

func (p *Info) InjectContext(ctx context.Context) context.Context {
	return InfoInjectContext(ctx, p)
}

func (v *Info) Init(ctx context.Context) error {
	return nil
}
