/*
Package archive GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package archive

import (
	courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(courier.NewRouter(&ArchiveZip{}))
}

func (ArchiveZip) ResponseContent() any {
	return new(ZipFile)
}

func (ArchiveZip) ResponseData() *ZipFile {
	return new(ZipFile)
}
