/*
Package archive GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package archive

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ArchiveZip{}))
}

func (*ArchiveZip) ResponseContent() any {
	return new(ZipFile)
}
