/*
Package archive GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package archive

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ArchiveZip) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {

		}

		return nil, false
	}
	return []string{}, true
}

func (v ZipFile) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "FileName":
			return []string{}, true
		case "Files":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
