// Code generated by gengo:operator DO NOT EDIT.
package v0

import (
	courier "github.com/octohelm/courier/pkg/courier"

	orgv0 "github.com/innoai-tech/infra/internal/example/pkg/apis/org/v0"
)

func init() {
	R.Register(courier.NewRouter(&CreateOrg{}))
}

func (CreateOrg) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&DeleteOrg{}))
}

func (DeleteOrg) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&GetOrg{}))
}

func (GetOrg) ResponseContent() any {
	return new(orgv0.Detail)
}

func init() {
	R.Register(courier.NewRouter(&ListOrg{}))
}

func (ListOrg) ResponseStatusCode() int {
	return 200
}

func (ListOrg) ResponseContent() any {
	return new(orgv0.DataList)
}
