/*
Package org GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package org

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&CreateOrg{}))
}

func (*CreateOrg) ResponseContent() any {
	return nil
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&DeleteOrg{}))
}

func (*DeleteOrg) ResponseContent() any {
	return nil
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&GetOrg{}))
}

func (*GetOrg) ResponseContent() any {
	return new(Detail)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListOrg{}))
}

func (*ListOrg) ResponseContent() any {
	return new(DataList)
}
