/*
Package main GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package main

type canRuntimeDoc interface {
	RuntimeDoc(names ...string) ([]string, bool)
}

func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(canRuntimeDoc); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Serve) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "C":
			return []string{}, true
		case "Otel":
			return []string{}, true
		case "Server":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.C, names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(v.Otel, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"Start serve",
	}, true
}
