// Code generated by gengo:runtimedoc DO NOT EDIT.
package otel

func (v *Otel) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "LogLevel":
			return []string{
				"日志级别",
			}, true
		case "LogFormat":
			return []string{
				"日志格式",
			}, true
		case "TraceCollectorEndpoint":
			return []string{
				"设置后将启用 trace 采集",
			}, true
		case "MetricCollectorEndpoint":
			return []string{}, true
		case "MetricCollectIntervalSeconds":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
