/*
Package otel GENERATED BY gengo:enum 
DON'T EDIT THIS FILE
*/
package otel

func (LogLevel) EnumValues() []any {
	return []any{
		DebugLevel, ErrorLevel, FatalLevel, InfoLevel, PanicLevel, TraceLevel, WarnLevel,
	}
}
