/*
Package cli GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package cli

type canRuntimeDoc interface {
	RuntimeDoc(names ...string) ([]string, bool)
}

func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(canRuntimeDoc); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v App) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Version":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v C) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Desc":
			return []string{}, true
		case "Args":
			return []string{}, true
		case "ValidArgs":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (ValidArgs) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
