/*
Package http GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package http

type canRuntimeDoc interface {
	RuntimeDoc(names ...string) ([]string, bool)
}

func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(canRuntimeDoc); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Server) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Addr":
			return []string{
				"Listen addr",
			}, true
		case "EnableDebug":
			return []string{
				"Enable debug mode",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
