// Code generated by gengo:runtimedoc DO NOT EDIT.
package http

func (v *Server) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Addr":
			return []string{
				"监听地址",
			}, true
		case "EnableDebug":
			return []string{
				"启用调试模式",
			}, true

		}

		return nil, false
	}
	return []string{
		"提供基于 courier 的 HTTP 服务装配能力。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
