package exporteddoccheck

import (
	"os"
	"path/filepath"
	"testing"

	. "github.com/octohelm/x/testing/v2"
)

func TestCheckDir(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()

	Must(t, func() error {
		return os.WriteFile(filepath.Join(dir, "doc.go"), []byte("package sample\n"), 0o600)
	})

	Must(t, func() error {
		return os.WriteFile(filepath.Join(dir, "sample.go"), []byte(`package sample

// WithDoc is documented.
type WithDoc struct{}

type MissingType struct{}

// Value is documented.
var Value = ""

var MissingValue = ""

// Do is documented.
func Do() {}

func MissingFunc() {}
`), 0o600)
	})

	findings, err := CheckDir(dir)
	if err != nil {
		t.Fatalf("CheckDir() error = %v", err)
	}

	Then(t, "CheckDir 返回缺失导出注释的顶层声明",
		Expect(findings, Equal([]Finding{
			{File: filepath.Join(dir, "sample.go"), Line: 6, Kind: "type", Name: "MissingType"},
			{File: filepath.Join(dir, "sample.go"), Line: 11, Kind: "var", Name: "MissingValue"},
			{File: filepath.Join(dir, "sample.go"), Line: 16, Kind: "func", Name: "MissingFunc"},
		})),
	)
}

func TestCheckPackagesSkipsGeneratedAndInternal(t *testing.T) {
	t.Parallel()

	root := t.TempDir()

	Must(t, func() error {
		return os.MkdirAll(filepath.Join(root, "pkg", "alpha"), 0o755)
	})
	Must(t, func() error {
		return os.MkdirAll(filepath.Join(root, "pkg", "internal", "beta"), 0o755)
	})

	Must(t, func() error {
		return os.WriteFile(filepath.Join(root, "pkg", "alpha", "alpha.go"), []byte(`package alpha
type Missing struct{}
`), 0o600)
	})

	Must(t, func() error {
		return os.WriteFile(filepath.Join(root, "pkg", "alpha", "zz_generated.runtimedoc.go"), []byte(`// Code generated by x DO NOT EDIT.
package alpha
type Ignored struct{}
`), 0o600)
	})

	Must(t, func() error {
		return os.WriteFile(filepath.Join(root, "pkg", "internal", "beta", "beta.go"), []byte(`package beta
type Hidden struct{}
`), 0o600)
	})

	findings, err := CheckPackages(filepath.Join(root, "pkg"))
	if err != nil {
		t.Fatalf("CheckPackages() error = %v", err)
	}

	Then(t, "CheckPackages 跳过 generated 和 internal 目录",
		Expect(findings, Equal([]Finding{
			{File: filepath.Join(root, "pkg", "alpha", "alpha.go"), Line: 2, Kind: "type", Name: "Missing"},
		})),
	)
}
