devkit := "go run " + clean(join(module_directory(), "./cmd/devkit"))

[group('meta')]
default:
    @just --list

# 整理依赖
[group("env")]
[no-cd]
dep: && skills-install
    {{ devkit }} workrun go mod tidy
    go work sync

# 更新依赖
[group("env")]
[no-cd]
update:
    {{ devkit }} workrun go get -u ./...

# 运行测试
[group("test")]
[no-cd]
test path='./...' *args:
    {{ devkit }} workrun -C={{ path }} go test -count=1 -failfast {{ args }} {}

# 格式化
[group("fmt")]
[no-cd]
fmt path='./...' *args="-l -w":
    {{ devkit }} workrun -C={{ path }} {{ devkit }} fmt {{ args }} {}

# 代码生成
[group("build")]
[no-cd]
gen path='./...' *args:
    {{ devkit }} workrun -C={{ path }} {{ devkit }} gen {{ args }} {}

# 安装 agent skills
[group("env")]
[no-cd]
skills-install:
    {{ devkit }} skills-install
