// Code generated by gengo:runtimedoc DO NOT EDIT.
package v0

func (v *DataList) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Data":
			return []string{}, true
		case "Total":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"表示组织列表响应体。",
	}, true
}

func (v *Detail) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Info, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"表示组织详情。",
	}, true
}

func (v *Info) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"组织名称",
			}, true
		case "Type":
			return []string{
				"组织类型",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示组织的基础信息。",
	}, true
}

func (*Type) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"表示组织类型。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
