/*
Package middleware GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package middleware

func (*CORSOption) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"represents a functional option for configuring the CORS middleware.",
	}, true
}

func (*OriginValidator) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"takes an origin string and returns whether or not that origin is allowed.",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
