/*
Package otel GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package otel

type canRuntimeDoc interface {
	RuntimeDoc(names ...string) ([]string, bool)
}

func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(canRuntimeDoc); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (OutputFilterType) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
