/*
Package otel GENERATED BY gengo:enum 
DON'T EDIT THIS FILE
*/
package otel

func (OutputFilterType) EnumValues() []any {
	return []any{
		OutputFilterAlways, OutputFilterNever, OutputFilterOnFailure,
	}
}
