// Code generated by gengo:operator DO NOT EDIT.
package v0

import (
	courier "github.com/octohelm/courier/pkg/courier"

	archivev0 "github.com/innoai-tech/infra/internal/example/pkg/apis/archive/v0"
)

func init() {
	R.Register(courier.NewRouter(&ArchiveZip{}))
}

func (ArchiveZip) ResponseContent() any {
	return new(archivev0.ZipFile)
}
